### ISSUE TITLE
PubSub Java Publisher error

### ISSUE THREAD

**Issue by VamshiGitHu** [developerforce/pub-sub-api#40]
I am getting a null pointer exception when publishing a message to Salesforce event 

<pre>2023-09-07 11:42:04,227 [main] java.lang.Class - Using grpcHost api.pubsub.salesforce.com and grpcPort 7443
2023-09-07 11:42:27,543 [main] java.lang.Class - Error During PublishStream
2023-09-07 11:42:27,552 [main] java.lang.Class -  === Exception ===
java.lang.NullPointerException: null
	at org.apache.avro.generic.GenericRecordBuilder.set(GenericRecordBuilder.java:124)
	at org.apache.avro.generic.GenericRecordBuilder.set(GenericRecordBuilder.java:113)
	at utility.CommonContext.createCarMaintenanceRecord(CommonContext.java:198)
	at genericpubsub.PublishStream.generateProducerEvent(PublishStream.java:123)
	at genericpubsub.PublishStream.generatePublishRequest(PublishStream.java:143)
	at genericpubsub.PublishStream.publishStream(PublishStream.java:68)
	at genericpubsub.PublishStream.main(PublishStream.java:203)
</pre>

Anyone faced this issue before? any guidance here is helpful. I am following steps from Salesforce documentation.

**Comment by johnboyer** [comment]
I have the same error. Were you ever able to track down the problem?
